

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace katselabor
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class katselaborEntities : DbContext
{
    public katselaborEntities()
        : base("name=katselaborEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<generationHistorySet> generationHistorySets { get; set; }

    public virtual DbSet<kogustetabel> kogustetabels { get; set; }

    public virtual DbSet<students> students { get; set; }

}

}

