
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace katselabor
{

using System;
    using System.Collections.Generic;
    
public partial class students
{

    public int Id { get; set; }

    public string name { get; set; }

    public string length { get; set; }

    public Nullable<decimal> mass { get; set; }

    public string sex { get; set; }

    public Nullable<System.DateTime> entryDate { get; set; }

}

}
